---
title: "R Notebook"
output: html_notebook
---

Start with a random walk on the soccer field:

```{r}
library(rethinking)
pos <- replicate( 1000 , sum( runif(16,-1,1) ) )
dens(pos, norm.comp=TRUE)
```



We can also get a normal distribution via multiplication when deviations are small:

```{r}
growth <- replicate( 10000 , prod( 1 + runif(12,0,0.1) ) )
dens( growth, norm.comp=TRUE)
```
For large deviations we need to put them on a log scale:

If deviations are larger we need to look at them on a log scale.

```{r}
growth <- replicate( 10000 , log(prod( 1 + runif(12,0,0.9) )) )
dens( growth, norm.comp=TRUE)
```

```{r}
big <- replicate( 10000 , prod( 1 + runif(12,0,0.5) ) )
small <- replicate( 10000 , prod( 1 + runif(12,0,0.01) ) )
dens( small, norm.comp=TRUE)
```

## Building the Regression Model

```{r}
library(rethinking)
data(Howell1)
d <- Howell1
precis(d)
```
Plot the priors:

```{r}
curve( dnorm( x , 178 , 20 ) , from=100 , to=250 )
```

```{r}
curve( dunif( x , 0 , 50 ) , from=-10 , to=60 )
```


```{r}
sample_mu <- rnorm( 1e4 , 178 , 100 )
sample_sigma <- runif( 1e4 , 0 , 50 )
prior_h <- rnorm( 1e4 , sample_mu , sample_sigma )
dens( prior_h )
```

Grid approximation of posterior

```{r}
d2 <- d[ d$age >= 18 , ]
mu.list <- seq( from=150, to=160 , length.out=100 )
sigma.list <- seq( from=7 , to=9 , length.out=100 )
post <- expand.grid( mu=mu.list , sigma=sigma.list )
post$LL <- sapply( 1:nrow(post) , function(i) sum(
  dnorm( d2$height , post$mu[i] , post$sigma[i] , log=TRUE ) ) )
post$prod <- post$LL + dnorm( post$mu , 178 , 20 , TRUE ) +
  dunif( post$sigma , 0 , 50 , TRUE )
post$prob <- exp( post$prod - max(post$prod) )
contour_xyz( post$mu , post$sigma , post$prob )
```

```{r}
image_xyz( post$mu , post$sigma , post$prob )
```   


```{r}
post
```







